name: Ejecutar Pruebas unitarias

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          npm install
          npm run build

      - name: Ejecutar pruebas de HTML y CSS
        run: |
          # Comandos para ejecutar pruebas de HTML y CSS (si aplicable)
